[package]
name = "sleep"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
system_shutdown = "4.0.1"
lock_keys = "*"
brightness = "0.5.0"
futures = "0.3.28"